FROM node:alpine

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ACCESS_REGION

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION=${AWS_ACCESS_REGION}

RUN apk update && apk upgrade && apk add nano


RUN apk --no-cache add python3 py3-pip

RUN  pip3 install --upgrade pip --break-system-packages \
  && pip3 install --no-cache-dir awscli --break-system-packages

# Downloading necessary configuration files
RUN aws s3 cp s3://stralom-deploys/financial/ssh/financial_deploy /root/.ssh/financial_deploy
RUN aws s3 cp s3://stralom-deploys/financial/ssh/financial_core_deploy /root/.ssh/financial_core_deploy
RUN aws s3 cp s3://stralom-deploys/financial/ssh/config /root/.ssh/config
# Set environment variables for git
ENV GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
# Install git and openssh-client for cloning private repos
RUN apk add git openssh-client
#

##
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts && \
    chmod 0400 /root/.ssh/financial_deploy /root/.ssh/financial_core_deploy && \
    eval "$(ssh-agent -s)" && \
    ssh-add /root/.ssh/financial_deploy && \
    ssh-add /root/.ssh/financial_core_deploy

WORKDIR /app


#Clone the private repository with submodules
RUN  git clone git@github.com:bStrano/Stralom-Financial-API.git .
RUN sed -i 's/git@github\.com:bStrano\/Stralom-Financial-Core\.git/ssh:\/\/github\.com-stralom-core\/bStrano\/Stralom-Financial-Core\.git/g' .gitmodules

RUN  git submodule update --init --recursive
RUN  git checkout master && git pull

RUN aws s3 cp s3://stralom-deploys/financial/api/.env.production /app/.env

COPY package.json /app
RUN yarn install

RUN yarn build
EXPOSE 3000

CMD ["yarn","start:prod"]
